version: '3.4'

services:
  alert:
    build:
      context: .
    volumes:
      - c:/Users/paul.j.otoole/Documents/flask-celery-example:/code
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    
